name: build

on:
  push:
    branches: ["2023"]
    tags:
      - "v*.*.*"

  pull_request:
    branches: ["2023"]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-20.04

    permissions:
      actions: write
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependancy
        run: cd ${{github.workspace}} && python3 ./utils/project.py env

      - name: Init submodule
        run: cd ${{github.workspace}} && python3 ./utils/project.py init

      - name: Build
        run: cd ${{github.workspace}} && python3 ./utils/project.py build

      - name: Test
        run: cd ${{github.workspace}} && python3 ./utils/project.py test

      - name: Pack runtime
        run: cd ${{github.workspace}} && python3 ./utils/project.py pack

      - uses: release-drafter/release-drafter@v5
        id: create_draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Create release
      #   run:  echo "release_name=$(date --date="8 hours" +v%Y.%m.%d.vv%H.%M)" >> $GITHUB_ENV

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{steps.create_draft.outputs.tag_name}}
          name: Release ${{steps.create_draft.outputs.name}}
          prerelease: false
          files: ${{github.workspace}}/Release.zip
